# Generated by Django 5.0.4 on 2025-04-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aichatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprompt',
            name='prompt',
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='context_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='prompt_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='response_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.visit'),
        ),
    ]
