# Generated by Django 5.0.4 on 2025-04-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_aiprompt_prompt_aiprompt_context_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
