# Generated by Django 5.0.4 on 2025-04-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_patient_doctor_alter_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprompt',
            name='info_status',
            field=models.CharField(choices=[('complete', 'Complete Information'), ('pending', 'Information Required'), ('updated', 'Information Updated')], default='complete', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='language_detected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='required_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
