# Generated by Django 4.2.7 on 2025-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatsession_aichatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('symptoms', 'Symptoms'), ('medication', 'Medication'), ('test_results', 'Test Results'), ('follow_up', 'Follow Up'), ('emergency', 'Emergency')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='has_unread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_read_by_patient',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
    ]
