# Generated by Django 4.2.7 on 2025-06-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatsession_category_chatsession_has_unread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprompt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chatsession'),
        ),
    ]
